### ISSUE TITLE
[Library][Manifest] android:allowBackup="true"

### ISSUE THREAD

**Issue by JonathanMercandalli** [MatteoBattilana/WeatherView#16]
Do you really need that line in your lib manifest? (see your full manifest [here](https://github.com/MatteoBattilana/WeatherView/blob/6ef268dee1b59656e043a579fdeff0ba5b0cadb4/library/src/main/AndroidManifest.xml#L5))

```xml
android:allowBackup="true"
```
----

On client app, could be nice to use `android:allowBackup="false"` too. For now, here the compilation error if the client app do not use allowBackup.

```
> Manifest merger failed : Attribute application@allowBackup value=(false) from AndroidManifest.xml:16:9-36
  	is also present at [com.github.MatteoBattilana:WeatherView:2.0.2] AndroidManifest.xml:12:9-35 value=(true).
  	Suggestion: add 'tools:replace="android:allowBackup"' to <application> element at AndroidManifest.xml:15:5-35:19 to override.
```

----

Thks a lot for your lib =)

**Comment by magneticflux-** [comment]
No, I don't think that's needed. I'll investigate and release a new version very soon.

**Comment by JonathanMercandalli** [comment]
Nice (and thank you for your quick answer 👍)

**Comment by magneticflux-** [comment]
@JonathanMercandalli `2.0.3` should fix your issue! If not, just reopen this issue and we can investigate further.

**Comment by JonathanMercandalli** [comment]
@magneticflux- gg, thks a lot
