### ISSUE TITLE
Snowfall size

### ISSUE THREAD

**Issue by aboutgaurav** [MatteoBattilana/WeatherView#19]
Hi 
@MatteoBattilana 
is it possible to change the size of snowfall particle?

**Comment by magneticflux-** [comment]
Currently, there is no way to change the size of the snow particles. More work would be needed to extract the precipitation information into individual classes for customization.

**Comment by MatteoBattilana** [comment]
I'm working on [custom-particles-size](https://github.com/MatteoBattilana/WeatherView/tree/custom-particle-size) branch. This will let you choose the particle size.

I'll update you once finished.

**Comment by MatteoBattilana** [comment]
I have just opened the [pull request](https://github.com/MatteoBattilana/WeatherView/pull/24) for this issue; you can try it directly or simply wait until it gets merged.

**Comment by MatteoBattilana** [comment]
These features have been added to the v3.0.0 WeatherView release.

See [v3.0.0 changelog](https://github.com/MatteoBattilana/WeatherView/releases/tag/3.0.0)
