### ISSUE TITLE
Improvement: add gravity

### ISSUE THREAD

**Issue by HugoGresse** [MatteoBattilana/WeatherView#2]
It will be awesome to add gravity to each particle. 
Changing angle is a quick idea but by adding an independant gravity using device sensor on each particle we will respond perfectly and the animation will also be perfect.

**Comment by MatteoBattilana** [comment]
I was working on it but during the last period I was busy with some university exams.
I'll continue this feature as soon as possibile.

Thank for the advice

**Comment by HugoGresse** [comment]
w00t, good luck, if you need some let me know.

**Comment by MatteoBattilana** [comment]
Hi, I've added this feature but it is only in the beta version. I have to fix some little graphic bugs.

Link to Beta section in ReadMe:
[Beta](https://github.com/MatteoBattilana/WeatherView#beta)

**Comment by HugoGresse** [comment]
just tested it, it seems to works great, you've added a limit to the rotation which seems a bit low, will be cool to have almost 90° rotation. Also, the gravity is fixed for each particle, it should change in live according the the orientationSensor

**Comment by MatteoBattilana** [comment]
I've added this feature in the 1.2.0 versione, please check the new release.
