### ISSUE TITLE
All blank

### ISSUE THREAD

**Issue by hatsune-miku** [MatteoBattilana/WeatherView#21]
WeatherView weatherView = findViewById(R.id.weatherView);
        weatherView.setWeather(Constants.WeatherStatus.SUN);
        weatherView.setFPS(60);
        weatherView.startAnimation();

it shows only blank

**Comment by magneticflux-** [comment]
Please indicate all relevant versions. WeatherView version, Android versions, etc.

**Comment by hatsune-miku** [comment]
Thanks for replying.

Here are all thirdparty libs I used in my app,
    implementation 'com.github.MatteoBattilana:WeatherView:2.0.3'
    implementation 'jp.wasabeef:recyclerview-animators:2.2.5'
    implementation 'com.fmy:fjpeg:1.0.0@aar'
    implementation 'com.race604.flyrefresh:library:2.0.0'
    implementation 'de.hdodenhof:circleimageview:2.2.0'
    implementation 'com.jaren:likeview:1.1.0'

Here is part of my layout file.
            <android.support.constraint.ConstraintLayout
                android:layout_width="match_parent"
                android:layout_height="400dp">
                <com.github.matteobattilana.weather.WeatherView
                    android:id="@+id/weatherView"
                    android:layout_width="match_parent"
                    android:layout_height="match_parent"
                    android:visibility="visible"/>
            </android.support.constraint.ConstraintLayout>

I tried to remove other thirdparty libs but WeatherView kept showing nothing.

On Android 8.1.0 and 8.0.0
Did I missed any essential setups?

**Comment by hatsune-miku** [comment]
Sorry for disturbing. I've solve this problem and it's my mistake...ToT
