### ISSUE TITLE
why did you switch from Leonids to Confetti?

### ISSUE THREAD

**Issue by francisco-huge** [MatteoBattilana/WeatherView#22]
is it just that Confetti has more active development (last commit in master is April 2019) over Leonids (last active in Sept 2018)?  Or was it for performance reasons?

just curious, thanks!

**Comment by magneticflux-** [comment]
Confetti seems to be under more active development (which is especially important for the Android ecosystem). There isn't really a performance difference between the two since they both animate based on the current time and initial conditions.

**Comment by francisco-huge** [comment]
ok thanks for the info! was just curious
