### ISSUE TITLE
Custom Rain  or change droplet size?

### ISSUE THREAD

**Issue by Fridaythe13thapp** [MatteoBattilana/WeatherView#23]
Is there any way to change the rain droplet to a custom image or atleast change its size?they're only ~2 pixel on my 6 inch test devices.

**Comment by MatteoBattilana** [comment]
Hi,
thanks for your suggestions. As soon as I can I will add this feature.

**Comment by MatteoBattilana** [comment]
I'm working on [custom-particles-size](https://github.com/MatteoBattilana/WeatherView/tree/custom-particle-size) branch.

I'll update you once finished.

**Comment by MatteoBattilana** [comment]
I have just opened the [pull request](https://github.com/MatteoBattilana/WeatherView/pull/24) for this issue; you can try it directly or simply wait until it gets merged.

**Comment by MatteoBattilana** [comment]
These features have been added to the v3.0.0 WeatherView release.

See [v3.0.0 changelog](https://github.com/MatteoBattilana/WeatherView/releases/tag/3.0.0)
