### ISSUE TITLE
No wiki  and also no proper guide to how to use.

### ISSUE THREAD

**Issue by vivekpanchal** [MatteoBattilana/WeatherView#27]
No Wiki also I found no proper guide to how to start the animation and everything,
I can only implement the library after that I am blank.
I don't find any good guide on how to use this library also I have set the weather data still nothing working. please provide step by step guide on how to use this library.

**Comment by MatteoBattilana** [comment]
Hi @vivekpanchal,

Can you provide your test device specifications? I'll try to figure out the problem.
Did you take a look at the [sample app](https://github.com/MatteoBattilana/WeatherView/tree/master/app)?

You're right about the lack of documentation, I've already scheduled a task that will be done as soon as possibile.

**Comment by MatteoBattilana** [comment]
I've just create a project, you can follow the develop process [here](https://github.com/MatteoBattilana/WeatherView/projects/2)

**Comment by snowf0x** [comment]
Hy! my activity files are in java, and I am blank how to use weatherView in java (i am stuck in 
` implementation 'com.github.MatteoBattilana:WeatherView:2.0.3' `
` weatherView.setWeather(Constants.WeatherStatus.RAIN)
                                .setOrientationMode(Constants.OrientationStatus.ENABLE)
                                .setRainParticles(60)
                                .setCurrentLifeTime(8000)
                                .startAnimation();`
It would be great if you can and how to use this library in java
